build: add env variables

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -92,10 +92,16 @@ jobs:
           docker exec postgres_container sh -c "pg_isready -U $POSTGRES_USER -h postgres_container -p 5432"
           docker exec postgres_container sh -c "PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USER -h postgres_container -p 5432 -c '\l'"
           docker exec -e PGPASSWORD=$POSTGRES_PASSWORD postgres_container sh -c "psql -U $POSTGRES_USER -h postgres_container -p 5432 -c 'CREATE DATABASE $POSTGRES_DB_TEST;'"
-
       - name: Verify Test Database
         run: |
           docker exec -e PGPASSWORD=$POSTGRES_PASSWORD postgres_container sh -c "psql -U $POSTGRES_USER -h postgres_container -p 5432 -l"
+
+      - name: Verify Test Database and List Tables
+        run: |
+          docker exec -e PGPASSWORD=$POSTGRES_PASSWORD postgres_container sh -c "psql -U $POSTGRES_USER -h postgres_container -p 5432 -lqt | cut -d \| -f 1 | grep -w $POSTGRES_DB_TEST || echo 'Database not found: $POSTGRES_DB_TEST'"
+          docker exec -e PGPASSWORD=$POSTGRES_PASSWORD postgres_container sh -c "psql -U $POSTGRES_USER -h postgres_container -p 5432 -d $POSTGRES_DB_TEST -c '\dt'"
+          docker exec -e PGPASSWORD=$POSTGRES_PASSWORD postgres_container sh -c "psql -U $POSTGRES_USER -h postgres_container -p 5432 -d $POSTGRES_DB_TEST -c '\d users'"
+          docker exec -e PGPASSWORD=$POSTGRES_PASSWORD postgres_container sh -c "psql -U $POSTGRES_USER -h postgres_container -p 5432 -d $POSTGRES_DB_TEST -c 'DROP TABLE IF EXISTS users CASCADE;'"
 
       - name: Run Backend tests
         run: |
